// Modern Deno.serve implementation - No imports required

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// You can use 'gemini-1.5-flash' or 'gemini-2.0-flash-lite'
const MODEL_NAME = 'gemini-1.5-flash'; 
const API_VERSION = 'v1beta';

Deno.serve(async (req) => {
  // 1. Handle CORS Preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // 2. Validate Method & Body
    if (req.method !== 'POST') {
      throw new Error(`Method ${req.method} not allowed`);
    }

    let body;
    try {
      body = await req.json();
    } catch (e) {
      throw new Error('Invalid JSON body');
    }

    const { prompt, systemPrompt } = body;

    if (!prompt) {
      throw new Error('Missing required field: prompt');
    }

    // 3. API Key Check
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) {
      console.error('Server Error: GEMINI_API_KEY is not set.');
      throw new Error('Server configuration error: API Key missing');
    }

    // 4. Construct Payload
    // Use the provided system prompt or a default one
    const finalSystemPrompt = systemPrompt || "You are a helpful AI assistant.";
    
    const payload = {
      contents: [{
        parts: [{
          text: `${finalSystemPrompt}\n\nUser: ${prompt}`
        }]
      }],
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048,
      },
      // Optional safety settings (can be adjusted as needed)
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" }
      ]
    };

    // 5. Call Gemini API
    const response = await fetch(`https://generativelanguage.googleapis.com/${API_VERSION}/models/${MODEL_NAME}:generateContent?key=${geminiApiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`Gemini API Error (${response.status}):`, errorText);
      throw new Error(`Gemini Provider Error: ${response.statusText}`);
    }

    const data = await response.json();
    
    // Safety check for empty response
    if (!data.candidates || data.candidates.length === 0) {
      console.error('Gemini returned no candidates:', JSON.stringify(data));
      throw new Error('No response generated by AI.');
    }

    const generatedText = data.candidates[0].content?.parts?.[0]?.text || "No text returned.";

    // 6. Return Success Response
    return new Response(JSON.stringify({
      success: true,
      response: generatedText,
      usage: data.usageMetadata || null
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error: any) {
    console.error('Function Error:', error.message);
    return new Response(JSON.stringify({
      success: false,
      error: error.message || 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});